# Java ????
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# --- ?????? ---

# 1. ??????? 1.21.1
minecraft_version=1.21.1

# 2. ????
minecraft_version_range=[1.21.1, 1.22)

# 3. NeoForge ????? 21.1.x (?? 1.21.1 ?????)
# ?? 21.2.1-beta ?? 1.21.2 ????????
neo_version=21.1.70

# 4. ??????
mod_id=dog_dog
mod_name=Dog Dog
mod_license=All Rights Reserved
mod_version=2.0.1
mod_group_id=com.EdDYON.dogdog
mod_authors=EdDYON

# 5. ??? (Parchment) ??
# ?????? 1.21.1
neogradle.subsystems.parchment.minecraftVersion=1.21.1
neogradle.subsystems.parchment.mappingsVersion=2024.11.17
